version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "⬆️ deps(rust)"
      include: scope
    groups:
      dev-tools:
        patterns:
          - "criterion"
          - "rstest"
          - "tempfile"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "⬆️ deps(ci)"
      include: scope
    ignore:
      - dependency-name: "dtolnay/rust-toolchain"
