# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "CheckpointRepository",
    "Engine",
    "ReadResult",
    "find_chunk_boundary",
    "flat_to_paged",
    "flat_to_paged_torch",
    "paged_to_flat",
]

@typing.final
class CheckpointRepository:
    r"""
    Labeled checkpoint repository.
    
    Wraps `tdb_engine::checkpoint::CheckpointRepository` so consumers
    can save engine snapshots under string labels with a
    monotonically increasing sequence per label, list / find latest,
    and restore the latest into a fresh directory.
    """
    def __new__(cls, root: builtins.str) -> CheckpointRepository:
        r"""
        Open a repository rooted at ``root`` (created lazily).
        """
    def save(self, engine: Engine, label: builtins.str) -> typing.Any:
        r"""
        Save ``engine``'s current state under ``label``. Returns a
        dict with ``label``, ``seq``, ``path``, and ``manifest``.
        """
    def list(self, label: typing.Optional[builtins.str] = None) -> builtins.list[typing.Any]:
        r"""
        Return all checkpoints, optionally filtered by ``label``.
        """
    def latest(self, label: builtins.str) -> typing.Optional[typing.Any]:
        r"""
        Latest checkpoint for ``label`` or ``None`` if none exist.
        """
    def restore_latest(self, label: builtins.str, target_dir: builtins.str) -> Engine:
        r"""
        Restore the latest checkpoint for ``label`` into ``target_dir``.
        """

@typing.final
class Engine:
    r"""
    `TardigradeDB` engine — persistent KV cache memory for LLM agents.
    
    Thread-safe: wrapped in `Arc<RwLock<>>` so multiple Python threads can
    hold shared read guards in parallel. Pack-read methods (`mem_read_pack`
    and its variants) acquire the read guard; write methods and `mem_read`
    (which performs SLB warm-promotion) acquire the exclusive write guard.
    A few read-only handles to internal substores are cached outside the
    lock (currently the text store) so the corresponding fast-path methods
    can serve without acquiring any guard at all.
    """
    def __new__(cls, path: builtins.str, segment_size: typing.Optional[builtins.int] = None, vamana_threshold: typing.Optional[builtins.int] = None) -> Engine:
        r"""
        Open or create a `TardigradeDB` engine at the given directory path.
        
        Optional configuration:
          - `segment_size`: Segment file size threshold in bytes (default: 256MB).
          - `vamana_threshold`: Cell count before activating Vamana ANN index (default: 10000).
        """
    def mem_write(self, owner: builtins.int, layer: builtins.int, key: numpy.typing.NDArray[numpy.float32], value: numpy.typing.NDArray[numpy.float32], salience: builtins.float, parent_cell_id: typing.Optional[builtins.int]) -> builtins.int:
        r"""
        Write key/value vectors to the engine (cell-level API).
        
        Prefer [`Engine::mem_write_pack`] for new code — the Pack API is
        the canonical interface for storing multi-layer KV caches.
        """
    def mem_write_batch(self, requests: typing.Sequence[typing.Any]) -> builtins.list[builtins.int]:
        r"""
        Write multiple cells in a single batch with one fsync (Batch Command).
        
        Each item is a tuple of (owner, layer, key, value, salience, parent).
        Returns a list of assigned cell IDs.
        """
    def mem_read(self, query_key: numpy.typing.NDArray[numpy.float32], k: builtins.int, owner: typing.Optional[builtins.int]) -> builtins.list[ReadResult]:
        r"""
        Read the top-k most relevant cells for a query key (cell-level API).
        
        Prefer [`Engine::mem_read_pack`] for new code — the Pack API returns
        complete multi-layer KV caches ready for injection.
        """
    def mem_read_tokens(self, query_tokens: numpy.typing.NDArray[numpy.float32], k: builtins.int, owner: typing.Optional[builtins.int]) -> builtins.list[ReadResult]:
        r"""
        Read top-k cells using a raw per-token query matrix (Direct Token Query API).
        
        Accepts a 2D `NumPy` array of shape `(n_tokens, dim)` directly, avoiding
        the Python-side `encode_per_token` round-trip (header build + flatten +
        `PyO3` copy + Rust header parse). The Rust engine builds the encoded key
        in one allocation and delegates to `mem_read`.
        """
    def set_refinement_mode(self, mode: builtins.str, alpha: typing.Optional[builtins.float] = None, beta: typing.Optional[builtins.float] = None, k_prime: typing.Optional[builtins.int] = None) -> None:
        r"""
        Configure post-retrieval refinement (vague-query rescue).
        
        `mode` selects the strategy: `"none"`, `"centered"`, `"whitened"`, `"prf"`.
        With `"prf"`, optional `alpha` (default 0.7), `beta` (default 0.3), and
        `k_prime` (default 3) tune the Rocchio expansion.
        """
    def refinement_mode(self) -> builtins.str:
        r"""
        Currently configured refinement mode as `"none" | "centered" | "whitened" | "prf"`.
        """
    def set_token_reweighting(self, enabled: builtins.bool) -> None:
        r"""
        Enable or disable corpus-mean distance token importance reweighting.
        
        When enabled, each per-token score is scaled by
        `1 - cosine(token, corpus_mean)` before aggregation — distinctive tokens
        carry more retrieval signal than tokens aligned with the mean activation.
        """
    def token_reweighting(self) -> builtins.bool:
        r"""
        Whether corpus-mean distance token importance reweighting is enabled.
        """
    def cell_importance(self, cell_id: builtins.int) -> typing.Optional[builtins.float]:
        r"""
        Get the current importance score of a cell.
        """
    def cell_tier(self, cell_id: builtins.int) -> typing.Optional[builtins.int]:
        r"""
        Get the current tier of a cell (0=Draft, 1=Validated, 2=Core).
        """
    def cell_count(self) -> builtins.int:
        r"""
        Total number of cells in the engine.
        """
    def trace_ancestors(self, cell_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Get transitive ancestors of a cell following causal edges.
        """
    def has_vamana(self) -> builtins.bool:
        r"""
        Whether the Vamana ANN index is active.
        """
    def advance_days(self, days: builtins.float) -> None:
        r"""
        Simulate passage of time for governance decay (testing utility).
        """
    def evict_draft_packs(self, importance_threshold: builtins.float, owner: typing.Optional[builtins.int] = None) -> builtins.int:
        r"""
        Evict Draft-tier packs below the importance threshold.
        """
    def sweep_now(self, hours: builtins.float = 0.0, eviction_threshold: builtins.float = 15.0) -> builtins.int:
        r"""
        Run a governance sweep synchronously.
        
        Advances importance decay by ``hours`` and evicts Draft-tier
        packs that fall below ``eviction_threshold``. Returns the
        number of packs evicted. Use after a known event when you
        want tier transitions visible before the next read.
        """
    def list_owners(self) -> builtins.list[builtins.int]:
        r"""
        Enumerate every owner with at least one pack stored.
        
        Returns owners in ascending order.
        """
    def schedule_evict_draft(self, fires_at_unix_secs: builtins.float, owner: builtins.int, threshold: builtins.float) -> builtins.int:
        r"""
        Schedule an ``evict_draft`` action to fire at
        ``fires_at_unix_secs`` (seconds since the Unix epoch).
        Returns the assigned schedule id.
        
        The schedule is persisted to a JSON sidecar before this
        returns and survives engine restart. Built-in actions
        are idempotent; the at-least-once delivery model gives
        fire-once-in-effect across crashes.
        """
    def cancel_scheduled(self, id: builtins.int) -> builtins.bool:
        r"""
        Cancel a previously-scheduled action. Returns ``True`` if
        the entry was found and removed.
        """
    def list_scheduled(self) -> builtins.list[typing.Any]:
        r"""
        List pending scheduled entries as dicts:
        ``{"id": int, "fires_at_unix_secs": float, "action": dict}``.
        Entries are sorted by fire time ascending.
        """
    def fire_due_scheduled(self) -> builtins.int:
        r"""
        Fire any actions whose `fires_at <= now`. Returns the
        number of actions that fired successfully. Use after a
        known event when you want scheduled work committed
        before the next tick of the background maintenance
        worker.
        """
    def owner_exists(self, owner: builtins.int) -> builtins.bool:
        r"""
        Return ``True`` iff the engine has at least one pack for ``owner``.
        """
    def delete_owner(self, owner: builtins.int) -> builtins.int:
        r"""
        Delete every pack belonging to ``owner``; return the count
        deleted. Unlike :py:meth:`evict_draft_packs`, this is
        unconditional — validated and core-tier packs are removed
        too. Returns ``0`` when the owner has no packs.
        """
    def snapshot(self, out_path: builtins.str) -> typing.Any:
        r"""
        Snapshot the engine state to a portable tar archive at
        ``out_path``. Returns the manifest as a dict with keys
        ``magic``, ``format_version``, ``created_at``, ``pack_count``,
        ``owner_count``, ``sha256``.
        
        ``out_path`` must be outside the engine's working directory —
        otherwise the tar walker would read its own output.
        """
    @staticmethod
    def restore_from(in_path: builtins.str, target_dir: builtins.str) -> Engine:
        r"""
        Restore a snapshot archive at ``in_path`` into ``target_dir``
        and return a freshly opened :class:`Engine`.
        
        ``target_dir`` must be empty or non-existent. Raises
        :py:exc:`RuntimeError` with a typed message on integrity,
        magic, version, or codec mismatch.
        """
    @staticmethod
    def open_with_write_buffer(path: builtins.str, max_batch_size: builtins.int, max_idle_ms: builtins.int = 0) -> Engine:
        r"""
        Open an engine at ``path`` with a streaming-ingest write
        buffer enabled. Buffered writes return their pack id
        synchronously and defer the fsync until the buffer reaches
        ``max_batch_size`` or :py:meth:`flush_buffer` is called.
        
        ``max_idle_ms`` is reserved for a future idle-timer flush
        (currently has no effect); pass ``0``.
        """
    def flush_buffer(self) -> None:
        r"""
        Drain the streaming write buffer. No-op when the
        engine was opened without a buffer or when the buffer is
        already empty.
        """
    def pipeline_stage_count(self) -> builtins.int:
        r"""
        Number of stages in the retrieval pipeline.
        """
    def store_synapsis(self, id: builtins.int, owner: builtins.int, lora_a: numpy.typing.NDArray[numpy.float32], lora_b: numpy.typing.NDArray[numpy.float32], scale: builtins.float, rank: builtins.int, d_model: builtins.int, last_used: typing.Optional[builtins.int] = None, quality: typing.Optional[builtins.float] = None) -> None:
        r"""
        Store a `LoRA` adapter entry. Arrays are f32 in Python, converted to f16 internally.
        """
    def load_synapsis(self, owner: builtins.int) -> builtins.list[typing.Any]:
        r"""
        Load all `LoRA` adapter entries for an owner.
        
        Returns list of dicts with f32 numpy arrays (f16 converted to f32 on return).
        """
    def status(self) -> typing.Any:
        r"""
        Snapshot of engine state for monitoring and diagnostics.
        
        Returns a dict with keys: `cell_count`, `pack_count`, `segment_count`,
        `slb_occupancy`, `slb_capacity`, `vamana_active`, `pipeline_stages`,
        `governance_entries`, `trace_edges`, `arena_bytes`, `arena_bytes_per_cell`.
        """
    def compact(self) -> typing.Any:
        r"""
        Compact storage by rewriting segments with dead cells.
        
        Returns a dict with `segments_compacted`, `cells_moved`, `bytes_reclaimed`.
        """
    def start_maintenance(self, sweep_interval_secs: builtins.float = 3600.0, compaction_interval_secs: builtins.float = 21600.0, eviction_threshold: builtins.float = 15.0, hours_per_tick: builtins.float = 1.0) -> None:
        r"""
        Start background maintenance (governance sweep + auto-compaction).
        """
    def stop_maintenance(self) -> None:
        r"""
        Stop background maintenance.
        """
    def is_maintenance_running(self) -> builtins.bool:
        r"""
        Whether background maintenance is currently running.
        """
    def maintenance_status(self) -> typing.Any:
        r"""
        Get maintenance statistics.
        """
    def mem_write_batch_packs(self, packs: typing.Sequence[tuple[builtins.int, numpy.typing.NDArray[numpy.float32], typing.Sequence[tuple[builtins.int, numpy.typing.NDArray[numpy.float32]]], builtins.float, typing.Optional[builtins.str]]]) -> builtins.list[builtins.int]:
        r"""
        Persist a known-size batch of packs with one coalesced fsync.
        
        Each pack is a tuple `(owner, retrieval_key, layer_payloads, salience, text)`
        where `layer_payloads` is a list of `(layer_idx, data)` tuples and `text`
        is optional. Returns a list of assigned pack ids, strictly increasing
        and aligned to the input order.
        
        Distinct from [`Engine::open_with_write_buffer`]: this is the eager
        "I have N packs in hand, persist them all now" path. If a streaming
        write buffer is configured, its pending entries are flushed first so
        the batch lands after them.
        
        An empty input returns an empty list and does not touch storage.
        """
    def mem_write_pack_tokens(self, owner: builtins.int, token_matrix: numpy.typing.NDArray[numpy.float32], layer_payloads: typing.Sequence[tuple[builtins.int, numpy.typing.NDArray[numpy.float32]]], salience: builtins.float, text: typing.Optional[builtins.str] = None, salience_mode: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Store a complete multi-layer KV pack from a raw per-token retrieval matrix.
        
        Accepts a 2D `NumPy` array of shape `(n_tokens, dim)` directly. The
        engine builds the encoded retrieval key in one allocation in Rust,
        avoiding the Python-side `encode_per_token` round-trip (header build +
        flatten + `PyO3` copy + Rust re-parse).
        
        Symmetric write-side counterpart to [`Engine::mem_read_tokens`]. Prefer
        this over [`Engine::mem_write_pack`] when the caller already has the
        retrieval tokens as a 2D matrix; use [`Engine::mem_write_pack`] when
        the key is already encoded.
        
        Returns the assigned pack ID. Raises `RuntimeError` (stable code
        `tdb::write::empty_token_matrix`) on an empty / malformed matrix —
        silently writing such a pack would create an unqueryable cell.
        """
    def mem_write_pack(self, owner: builtins.int, retrieval_key: numpy.typing.NDArray[numpy.float32], layer_payloads: typing.Sequence[tuple[builtins.int, numpy.typing.NDArray[numpy.float32]]], salience: builtins.float, text: typing.Optional[builtins.str] = None, salience_mode: typing.Optional[builtins.str] = None) -> builtins.int:
        r"""
        Store a complete multi-layer KV cache as a single atomic pack.
        
        Returns the assigned pack ID.
        """
    def add_view_keys(self, pack_id: builtins.int, view_keys: typing.Sequence[numpy.typing.NDArray[numpy.float32]]) -> builtins.int:
        r"""
        Register one or more view keys for an existing pack.
        
        View keys are additional retrieval keys — queries matching any view key
        will surface this pack during `mem_read_pack`. Returns the total number
        of view keys registered for this pack after the call.
        """
    def view_count(self, pack_id: builtins.int) -> builtins.int:
        r"""
        Return the number of view keys registered for a pack.
        
        Raises `RuntimeError` if the pack does not exist.
        """
    def mem_write_pack_with_auto_link(self, owner: builtins.int, retrieval_key: numpy.typing.NDArray[numpy.float32], layer_payloads: typing.Sequence[tuple[builtins.int, numpy.typing.NDArray[numpy.float32]]], salience: builtins.float, auto_link_threshold: typing.Optional[builtins.float] = None, text: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Store a pack with automatic discovery and linking of similar existing packs.
        
        Returns a dict with `pack_id` and `linked_pack_ids`.
        Threshold defaults to [`DEFAULT_AUTO_LINK_THRESHOLD`] (250.0) when omitted.
        """
    def mem_read_pack(self, query_key: numpy.typing.NDArray[numpy.float32], k: builtins.int, owner: typing.Optional[builtins.int] = None, *, mode: builtins.str = 'unconfirmed', timeout_ms: typing.Optional[builtins.int] = None) -> builtins.list[typing.Any]:
        r"""
        Retrieve the top-k KV Packs matching a query key.
        
        Returns list of dicts with pack ID, owner, score, tier, and layers.
        
        **Read-visibility modes.** ``mode`` selects the durability
        contract for this read. Default ``"unconfirmed"`` returns
        immediately with whatever the retrieval pipeline currently
        sees — backwards-compatible with every existing caller.
        ``mode="confirmed"`` snapshots the issued offset at request
        entry, runs the retrieval, then blocks until the durable
        offset catches up (every concurrent in-flight write is now
        durable when the call returns). Confirmed reads MUST supply
        ``timeout_ms``; raises ``ValueError`` otherwise.
        """
    def mem_read_pack_batch(self, queries: typing.Sequence[numpy.typing.NDArray[numpy.float32]], k: typing.Any, owner: typing.Any) -> builtins.list[builtins.list[typing.Any]]:
        r"""
        Batch read: run N retrievals in one `PyO3` crossing.
        
        `queries` is a list of 1-D float32 ndarrays; the call returns a
        `list[list[dict]]` aligned by input position. `k` and `owner`
        each accept a scalar (broadcast across all queries) or a list of
        length `len(queries)` for per-query specialisation. `owner` list
        entries may be `None` to skip the filter for that one query.
        
        Behaviour is identical to calling [`Engine::mem_read_pack`] N
        times — this method exists to amortise `PyO3` crossing cost and
        to give consumers a single point of entry for multi-agent /
        multi-NPC fanout queries.
        """
    def mem_read_multi_layer(self, query_keys: typing.Sequence[numpy.typing.NDArray[numpy.float32]], k: builtins.int, owner: typing.Optional[builtins.int] = None, rrf_k: builtins.int = 60) -> builtins.list[typing.Any]:
        r"""
        Multi-layer query fusion via Reciprocal Rank Fusion.
        
        One engine call hides the N-query fanout + RRF merge that the
        Python `multi_layer_query` helper previously implemented in
        `tardigrade_hooks`. Each query key typically comes from a
        different transformer layer's hidden state; the engine fetches
        `k * 2` candidates per layer and fuses them.
        """
    def pack_count(self) -> builtins.int:
        r"""
        Number of KV Packs stored.
        """
    def refresh(self) -> None:
        r"""
        Re-sync in-memory state from disk.
        
        Use when another process or `Engine` handle has written to the same
        directory and this handle needs to see those writes. Re-applies the
        Memento pattern from `open()`: rescans segments, replays the WAL,
        refreshes governance / `pack_directory` / `text_store` / `deletion_log`.
        Idempotent and cheap when nothing changed on disk.
        """
    def pack_importance(self, pack_id: builtins.int) -> typing.Optional[builtins.float]:
        r"""
        Get the importance score of a pack.
        """
    def list_packs_metadata(self, owner: typing.Optional[builtins.int] = None) -> typing.Any:
        r"""
        Enumerate pack metadata (no text) as a struct-of-arrays.
        
        Returns a dict of four parallel numpy arrays, all of length N:
        * `pack_ids`   — `np.uint64[N]`
        * `owners`     — `np.uint64[N]`
        * `tiers`      — `np.uint8[N]`  (0=Draft, 1=Validated, 2=Core)
        * `importances`— `np.float32[N]`
        
        Rows are aligned by index and sorted by importance descending.
        
        The columnar shape lets the call answer from `PackDirectory`'s
        in-memory indices via a single Rust→Python crossing, with no per-row
        Python dict allocation. Use [`Engine::list_packs`] with
        `fetch_text=True` when you need text alongside the metadata.
        """
    def load_embedding_table(self, weights: numpy.typing.NDArray[numpy.float32]) -> None:
        r"""
        Load the model's token-embedding table into the engine.
        
        `weights` is a `(vocab_size, hidden_size)` float32 ndarray. The
        engine takes a flat owned copy so the call is safe even if the
        caller drops or mutates `weights` afterwards. Repeated calls
        replace the previous table; the load counter is incremented.
        """
    def embedding_table_load_count(self) -> builtins.int:
        r"""
        Number of `load_embedding_table` calls (observability counter).
        """
    def set_projection_matrix(self, matrix: numpy.typing.NDArray[numpy.float32]) -> None:
        r"""
        Install a projection matrix for the `"projected"` strategy.
        
        `matrix` is a `(kv_dim, hidden_size)` float32 ndarray.
        """
    def compute_retrieval_key(self, token_ids: typing.Sequence[builtins.int], strategy: builtins.str = 'last_token') -> typing.Optional[numpy.typing.NDArray[numpy.float32]]:
        r"""
        Compute a retrieval key from `token_ids` via the named strategy.
        
        Returns the key as a 1-D float32 ndarray, or `None` when the
        embedding table has not been loaded, when `token_ids` is empty,
        or when every id is out of vocabulary range. Raises
        `ValueError` when `strategy` is not one of `"last_token"`,
        `"mean_pool"`, `"projected"`.
        """
    def set_fingerprint_capacity(self, capacity: builtins.int) -> None:
        r"""
        Configure (or resize) the engine-side fingerprint LRU cache.
        
        `capacity` matches the vLLM scheduler's `max_num_seqs` in
        practice — keeps the cache exactly large enough to hold every
        concurrently in-flight request and no larger, so a finished
        request's fingerprint cannot survive into a new request that
        reuses the same block id.
        """
    def fingerprint_get(self, fingerprint: builtins.int) -> typing.Optional[builtins.int]:
        r"""
        Lookup the pack id last written for this fingerprint.
        Returns `None` when absent or when the cache has not been
        sized yet via [`Engine::set_fingerprint_capacity`].
        """
    def fingerprint_put(self, fingerprint: builtins.int, pack_id: builtins.int) -> None:
        r"""
        Store `pack_id` for this fingerprint, evicting the LRU entry
        when the cache is full.
        """
    def fingerprint_release(self, fingerprint: builtins.int) -> None:
        r"""
        Drop the entry for this fingerprint (no-op when absent).
        Call from the connector's `request_finished` lifecycle hook.
        """
    def fingerprint_len(self) -> builtins.int:
        r"""
        Current number of fingerprint entries (observability hook).
        """
    def list_packs(self, owner: typing.Optional[builtins.int] = None, *, fetch_text: builtins.bool) -> typing.Any:
        r"""
        Enumerate all packs as a list of dicts, with text included.
        
        Returns a list of dicts with keys: `pack_id`, `owner`, `tier`, `importance`, `text`.
        Sorted by importance descending.
        
        **Performance note:** this shape allocates one Python dict per pack, which
        dominates wall time at scale. When you don't need text, prefer
        [`Engine::list_packs_metadata`] — it returns parallel numpy arrays from a
        single Rust→Python crossing.
        
        `fetch_text` is a required keyword argument. Pass `True` to populate
        the `text` field via a per-pack lookup. Pass `False` to skip the
        lookup and emit `None` for every `text` entry — useful when only
        metadata is needed but the list-of-dicts shape is still convenient.
        For pure metadata enumeration prefer [`Engine::list_packs_metadata`].
        """
    def load_pack_by_id(self, pack_id: builtins.int) -> typing.Any:
        r"""
        Load a pack by ID without retrieval scoring.
        """
    def add_pack_edge(self, pack_id_1: builtins.int, pack_id_2: builtins.int, edge_type: builtins.int) -> None:
        r"""
        Create a durable typed trace edge between two packs.
        
        `edge_type`: 0=CausedBy, 1=Follows, 2=Contradicts, 3=Supports.
        """
    def add_pack_link(self, pack_id_1: builtins.int, pack_id_2: builtins.int) -> None:
        r"""
        Create a durable Follows link between two packs.
        """
    def pack_links(self, pack_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Get all packs linked to a given pack via trace edges (any type).
        """
    def pack_links_by_type(self, pack_id: builtins.int, edge_type: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Get packs linked via a specific edge type.
        """
    def pack_supports(self, pack_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Get packs that support a given pack.
        """
    def pack_contradicts(self, pack_id: builtins.int) -> builtins.list[builtins.int]:
        r"""
        Get packs that contradict a given pack.
        """
    def mem_read_pack_with_trace_boost(self, query_key: numpy.typing.NDArray[numpy.float32], k: builtins.int, owner: typing.Optional[builtins.int], boost_factor: builtins.float) -> builtins.list[typing.Any]:
        r"""
        Retrieve packs with trace-boosted scoring.
        """
    def mem_read_pack_with_trace_boost_and_follow(self, query_key: numpy.typing.NDArray[numpy.float32], k: builtins.int, owner: typing.Optional[builtins.int], boost_factor: builtins.float) -> builtins.list[typing.Any]:
        r"""
        Retrieve packs with trace-boosted scoring and automatic link traversal.
        """
    def pack_text(self, pack_id: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Get the stored text for a pack, if any.
        
        Lock-free: served directly from the cached `Arc<TextStore>` handle
        without acquiring the engine mutex. Multiple Python threads can
        call `pack_text` simultaneously even while another thread holds
        the engine lock for an unrelated operation.
        """
    def set_pack_text(self, pack_id: builtins.int, text: builtins.str) -> None:
        r"""
        Set or update the stored text for an existing pack.
        """
    def set_pack_texts(self, entries: typing.Sequence[tuple[builtins.int, builtins.str]]) -> None:
        r"""
        Set or update text for many packs in a single batched fsync.
        """
    def pack_exists(self, pack_id: builtins.int) -> builtins.bool:
        r"""
        Whether a pack with the given ID exists (and has not been deleted).
        """
    def delete_pack(self, pack_id: builtins.int) -> None:
        r"""
        Delete a pack permanently. Irreversible.
        """
    def flush(self) -> None:
        r"""
        Explicit durability checkpoint — ensures all components have fsynced.
        """
    def durable_offset(self) -> builtins.int:
        r"""
        Current durable offset — monotonic counter that advances every
        time an fsync completes. Consumers reasoning about the
        durability boundary (e.g., the confirmed-read API) snapshot
        this value and wait for it to reach a target. See the
        "Reliability & Consistency Rules" section of CLAUDE.md.
        """
    def metrics_prometheus_text(self) -> builtins.str:
        r"""
        Render the process-wide Prometheus registry to text exposition
        format. The same text the HTTP bridge serves at ``/metrics``;
        exposed directly here so embedded consumers can scrape without
        going through HTTP.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ReadResult:
    r"""
    A single retrieval result returned from `mem_read`.
    """
    @property
    def cell_id(self) -> builtins.int: ...
    @property
    def owner(self) -> builtins.int: ...
    @property
    def layer(self) -> builtins.int: ...
    @property
    def score(self) -> builtins.float: ...
    @property
    def tier(self) -> builtins.int: ...
    @property
    def importance(self) -> builtins.float: ...
    def key(self) -> builtins.list[builtins.float]:
        r"""
        Get the key vector as a list of floats.
        """
    def value(self) -> builtins.list[builtins.float]:
        r"""
        Get the value vector as a list of floats.
        """
    def __repr__(self) -> builtins.str: ...

def find_chunk_boundary(text: builtins.str, max_pos: builtins.int, strategy: builtins.str) -> builtins.int:
    r"""
    Find a byte position `<= max_pos` to split `text` at, preferring the
    natural boundary indicated by `strategy`.
    
    `strategy` is one of `"whitespace"`, `"sentence"`, or `"paragraph"`.
    See `tdb_engine::chunk_boundary` for the precise semantics — this is
    a direct `PyO3` surface over the Rust function.
    """

def flat_to_paged(flat_kv: numpy.typing.NDArray[numpy.float32], num_kv_heads: builtins.int, head_dim: builtins.int, block_size: builtins.int) -> tuple[numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Convert a flat `[K_flat | V_flat]` ndarray into vLLM paged blocks.
    
    Returns `(k_blocks, v_blocks)` as 1-D float32 ndarrays of length
    `num_blocks * block_size * num_kv_heads * head_dim`. Reshape in
    Python with `.reshape(num_blocks, block_size, num_kv_heads, head_dim)`
    to recover the four-axis layout. Stateless — does not touch the engine.
    """

def flat_to_paged_torch(flat_kv: typing.Any, num_kv_heads: builtins.int, head_dim: builtins.int, block_size: builtins.int) -> tuple[numpy.typing.NDArray[numpy.float32], numpy.typing.NDArray[numpy.float32]]:
    r"""
    Torch-tensor variant of [`flat_to_paged`]. Reads the tensor's raw
    buffer via `data_ptr()` directly — no numpy intermediary, no
    libtorch link, no `tch-rs` dependency. The consumer's installed
    torch handles all the C++ side; Rust just reads the memory.
    
    Requires the tensor to be a contiguous CPU float32 buffer. CUDA
    tensors, non-contiguous views, and non-f32 dtypes get rejected
    with a clear error — converting them is a Python-side responsibility
    (`tensor.cpu().contiguous().to(torch.float32)`).
    """

def paged_to_flat(k_blocks: numpy.typing.NDArray[numpy.float32], v_blocks: numpy.typing.NDArray[numpy.float32], seq_len: builtins.int, num_kv_heads: builtins.int, head_dim: builtins.int) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Convert vLLM paged K/V blocks back into a flat `[K_flat | V_flat]`
    float32 ndarray. Stateless — does not touch the engine.
    """

