// Minimal Node.js consumer for the TardigradeDB HTTP bridge.
//
// The script exercises the foundation surface end-to-end:
//   1. store five facts under owner 1
//   2. query a fact back and assert the round-trip
//   3. snapshot the engine to a tar archive
//   4. restore the snapshot into a fresh directory and assert pack count
//
// No engine internals are touched — everything goes through HTTP.
// Type definitions for the bridge live in
// python/tardigrade_http/types.ts (regenerated by `npm run gen-types`
// at the repo root, or `npx openapi-typescript schema.yaml -o types.ts`).
//
// Usage:
//   BRIDGE_URL=http://127.0.0.1:8765 \
//   SNAPSHOT_PATH=/tmp/demo-snap.tar \
//   RESTORE_DIR=/tmp/demo-restored \
//   node examples/nodejs_consumer/index.mjs

import { strict as assert } from "node:assert";

const BRIDGE_URL = process.env.BRIDGE_URL ?? "http://127.0.0.1:8765";
const SNAPSHOT_PATH = process.env.SNAPSHOT_PATH ?? "/tmp/demo-snap.tar";
const RESTORE_DIR = process.env.RESTORE_DIR ?? "/tmp/demo-restored";
const OWNER = 1;
const FACTS = [
  "the engine is owner-scoped",
  "snapshots include magic and version",
  "writes default to per-cell fsync",
  "the write buffer coalesces fsyncs into batches",
  "retrieval is a per-token latent-space scoring pass",
];

async function unwrap(path, r) {
  // Read the body once; reuse it for both the OK path and the
  // error message. Calling `r.text()` after `r.json()` (or vice
  // versa) trips Node's "Body has already been read" guard.
  const raw = await r.text();
  if (r.status !== 200) {
    throw new Error(`${path} returned ${r.status}: ${raw}`);
  }
  return JSON.parse(raw);
}

async function post(path, body) {
  const r = await fetch(`${BRIDGE_URL}${path}`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  return unwrap(path, r);
}

async function get(path) {
  return unwrap(path, await fetch(`${BRIDGE_URL}${path}`));
}

const packIds = [];
for (const fact of FACTS) {
  const { pack_id } = await post("/mem/store", { owner: OWNER, fact_text: fact });
  packIds.push(pack_id);
}
console.log(`stored ${packIds.length} facts → pack_ids ${packIds.join(", ")}`);

const target = FACTS[2];
const { results } = await post("/mem/query", { owner: OWNER, query_text: target, k: 5 });
assert.ok(
  results.some((r) => r.pack_id === packIds[2]),
  `expected pack ${packIds[2]} in query results, got ${JSON.stringify(results)}`,
);
console.log(`query "${target}" → ${results.length} results, target pack matched`);

const { manifest } = await post("/mem/save", { snapshot_path: SNAPSHOT_PATH });
assert.equal(manifest.magic, "tdb!", `bad magic ${manifest.magic}`);
assert.equal(manifest.pack_count, FACTS.length, `manifest pack_count ${manifest.pack_count}`);
console.log(`snapshot → ${SNAPSHOT_PATH} (sha256 ${manifest.sha256.slice(0, 12)}…)`);

const restored = await post("/mem/restore", {
  snapshot_path: SNAPSHOT_PATH,
  target_dir: RESTORE_DIR,
});
assert.equal(restored.ok, true);
assert.equal(restored.pack_count, FACTS.length);
console.log(`restored → ${RESTORE_DIR}, ${restored.pack_count} packs intact`);

const { owners } = await get("/mem/owners");
assert.deepEqual(owners, [OWNER], `unexpected owners ${owners}`);
console.log(`owners = ${JSON.stringify(owners)} ✓`);
