/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/mem/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store */
        post: operations["store_mem_store_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mem/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_mem_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mem/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owners */
        get: operations["owners_mem_owners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mem/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_mem_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mem/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save */
        post: operations["save_mem_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mem/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_mem_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Manifest
         * @description Mirror of :class:`tdb_engine::snapshot::SnapshotManifest`.
         *
         *     Field names match the Rust struct so consumers can rely on a
         *     stable wire contract across languages.
         */
        Manifest: {
            /** Magic */
            magic: string;
            /** Format Version */
            format_version: number;
            /** Created At */
            created_at: string;
            /** Pack Count */
            pack_count: number;
            /** Owner Count */
            owner_count: number;
            /** Sha256 */
            sha256: string;
            /** Quantization Codec */
            quantization_codec: string;
            /** Key Codec */
            key_codec: string;
        };
        /** OwnersResponse */
        OwnersResponse: {
            /** Owners */
            owners: number[];
        };
        /**
         * QueryRequest
         * @description Body of ``POST /mem/query``.
         */
        QueryRequest: {
            /** Owner */
            owner: number;
            /** Query Text */
            query_text: string;
            /**
             * K
             * @default 5
             */
            k: number;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Results */
            results: components["schemas"]["QueryResult"][];
        };
        /** QueryResult */
        QueryResult: {
            /** Pack Id */
            pack_id: number;
            /** Score */
            score: number;
            /** Text */
            text?: string | null;
        };
        /**
         * RestoreRequest
         * @description Body of ``POST /mem/restore``.
         *
         *     Restores the snapshot at ``snapshot_path`` into ``target_dir``;
         *     the bridge does *not* hot-swap its running engine. To use the
         *     restored engine the consumer should relaunch the bridge with
         *     ``TARDIGRADE_HTTP_DB=target_dir``.
         */
        RestoreRequest: {
            /** Snapshot Path */
            snapshot_path: string;
            /** Target Dir */
            target_dir: string;
        };
        /** RestoreResponse */
        RestoreResponse: {
            /** Ok */
            ok: boolean;
            /** Pack Count */
            pack_count: number;
        };
        /**
         * SaveRequest
         * @description Body of ``POST /mem/save``.
         *
         *     Snapshots are engine-wide — they capture the whole working
         *     directory, not a single owner. ``snapshot_path`` must be
         *     outside the engine's directory (the bridge propagates the
         *     engine's foot-gun guard).
         */
        SaveRequest: {
            /** Snapshot Path */
            snapshot_path: string;
        };
        /** SaveResponse */
        SaveResponse: {
            manifest: components["schemas"]["Manifest"];
        };
        /**
         * StatusResponse
         * @description Mirror of :meth:`Engine.status` dict.
         */
        StatusResponse: {
            /** Cell Count */
            cell_count: number;
            /** Pack Count */
            pack_count: number;
            /** Segment Count */
            segment_count: number;
            /** Slb Occupancy */
            slb_occupancy: number;
            /** Slb Capacity */
            slb_capacity: number;
            /** Vamana Active */
            vamana_active: boolean;
            /** Pipeline Stages */
            pipeline_stages: number;
            /** Governance Entries */
            governance_entries: number;
            /** Trace Edges */
            trace_edges: number;
            /** Arena Bytes */
            arena_bytes: number;
            /** Arena Bytes Per Cell */
            arena_bytes_per_cell: number;
        };
        /**
         * StoreRequest
         * @description Body of ``POST /mem/store``.
         */
        StoreRequest: {
            /**
             * Owner
             * @description Owner ID for the memory.
             */
            owner: number;
            /**
             * Fact Text
             * @description Fact to remember.
             */
            fact_text: string;
            /**
             * Salience
             * @description Initial importance score in [0, 100].
             * @default 80
             */
            salience: number;
        };
        /** StoreResponse */
        StoreResponse: {
            /** Pack Id */
            pack_id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    store_mem_store_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_mem_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    owners_mem_owners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnersResponse"];
                };
            };
        };
    };
    status_mem_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    save_mem_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_mem_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
